@startmindmap
* Feign
** clients
*** java.net.URL
*** Apache HTTP
*** Apache HC5
*** Google HTTP
*** Java 11 Http2
*** OK Http
*** Ribbon
** async clients
*** java.net.URL
*** Apache HC5
*** OkHttp
*** Vertx
** contracts
*** Feign
*** JAX-RS
*** JAX-RS 2
*** JAX-RS 3 / Jakarta
*** Spring 5
*** SOAP
*** SOAP Jakarta
*** Spring boot (3rd party)

left side

** encoders/decoders
*** GSON
*** JAXB
*** JAXB Jakarta
*** Jackson 1
*** Jackson 2
*** Jackson JAXB
*** Jackson Jr
*** Sax
*** JSON-java
*** Moshi
*** Fastjson2
** metrics
*** Dropwizard Metrics 5
*** Micrometer
** extras
*** Hystrix
*** SLF4J
*** Mock
*** Annotation Error Decoder
@endmindmap
