@startmindmap
* Feign
** clients
*** java.net.URL
*** Apache HTTP
*** Apache HC5
*** Google HTTP
*** Java 11 Http2
*** OK Http
*** Ribbon
** async clients
*** java.net.URL
*** Apache HC5
*** OkHttp
*** Vertx
*** Reactive Wrappers
** contracts
*** Feign
*** JAX-RS
*** JAX-RS 2
*** JAX-RS 3 / Jakarta
*** JAX-RS 4
*** Spring
*** SOAP
*** SOAP Jakarta
*** Spring boot (3rd party)
** language
*** Kotlin
*** GraphQL

left side

** encoders/decoders
*** GSON
*** JAXB
*** JAXB Jakarta
*** Jackson
*** Jackson 3
*** Jackson JAXB
*** Jackson Jr
*** Sax
*** JSON-java
*** Moshi
*** Fastjson2
*** Form
*** Form Spring
** metrics
*** Dropwizard Metrics 4
*** Dropwizard Metrics 5
*** Micrometer
** extras
*** Hystrix
*** SLF4J
*** Mock
*** Annotation Error Decoder
@endmindmap
